### ISSUE TITLE
mobsim

### ISSUE THREAD

**Issue by renatamuy** [NINAnor/oneimpact#8]
Hi Ber, I think you use mobsim in the examples, but this package was removed from cran this year:

https://cran.r-project.org/web/packages/mobsim/index.html

**Comment by bniebuhr** [comment]
Hi Re,
Thanks for letting me know. The functions of these package are not essential to `oneimpact`, so I should probably replace it for other functions. 

I am currently using it to create a given number of patches of a given size to simulate landscape with different configurations, which is helpful to test the ZoI metrics under different conditions.
Do you happen to know of other functions from packages on CRAN to do something similar?

**Comment by renatamuy** [comment]
Hi Ber, 

I am not sure of packages for that on CRAN from memory, but you could just add this to the examples for now and keep using mobsim for now.

`devtools::install_github("MoBiodiv/mobsim", build_vignettes = FALSE)`

**Comment by bniebuhr** [comment]
Good! Since it is within the package and the function is also used by another package function (`set_points`) I added this package as a suggested remote package to be installed from Github in the DESCRIPTION file, here in commits e7519f02c77564f6486906669d7bd3e3e7482dba, 1ac0d6f0555164adb5bfa062ec67276f75c340a2, and 1024e7234449a38f6f889d21db1065c500f1b3f8
I did the same for the package NLMR.
